[package]
name = "sui_stack_messaging"
edition = "2024"

[dependencies]
sui_groups = { git = "https://github.com/MystenLabs/sui-groups.git", subdir = "move/packages/sui_groups", rev = "main" }
suins = { r.mvr = "@suins/core" }
