[package]
name = "example_app"
edition = "2024"

[dependencies]
sui_stack_messaging = { local = "../sui_stack_messaging" }
sui_groups = { git = "https://github.com/MystenLabs/sui-groups.git", subdir = "move/packages/sui_groups", rev = "main" }
